server {
    #listen 80;
    listen 443 ssl;

    server_name xxx.tech;

    client_max_body_size 10240m;

    allow 47.79.234.238;
    allow 223.166.7.32;
    allow 139.226.35.11;
    deny  all;

    # SSL 证书
    ssl_certificate     /etc/nginx/cert/xxx.crt;
    ssl_certificate_key /etc/nginx/cert/xxx.key;

    # 把 403 转成 404
    error_page 403 =404 /404.html;

    location = /404.html {
        internal;
        return 404;
    }

    location / {
        #proxy_set_header Host $host;
        proxy_set_header Host index-tts.shuoyao.tech;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Forwarded-Proto $scheme;
        #proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;

        proxy_redirect http:// https://;

        proxy_pass http://127.0.0.1:2443;
    }
}