apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
  - name: test-container
    image: swr.cn-east-3.myhuaweicloud.com/r4in/busybox:1.37.0
    command: ["/bin/sh"]
    args: ["-c", "echo test > /data/test.txt && ls -l /data && cat /data/test.txt && sleep 1"]
    volumeMounts:
    - name: pvc-volume
      mountPath: /data
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: test-pvc