# =========================
# 1. 提取 Authorization Key
# =========================
map $http_authorization $auth_key {
    default "";
    ~*^Bearer\s+(.+)$ $1;
}

# =========================
# 2. 仅对 500 并发的 key 生效
# =========================
map $auth_key $conn_key_500 {
    default "";

    # 目标 key（500 并发）
    "sk-A6iL7xQB4fPUI0wSskZpSEzsbclkIEgWZZcicOTOJmK80Dw0" $auth_key;
}

map $auth_key $conn_key_5 {
    default "";

    # 目标 key（5 并发）
    "sk-okbNTxeLX7KotKIqy26DNaembeiOW3hXKzvKpIsWtAobJzSi" $auth_key;
}



# 500 并发
limit_conn_zone $conn_key_500 zone=conn_auth_500:50m;
limit_conn_zone $conn_key_5 zone=conn_auth_5:50m;

