# 定义 Service，用于暴露外部服务
apiVersion: v1
kind: Service
metadata:
  name: llm
  namespace: monitor
  labels:
    app: llm
spec:
  ports:
    - port: 30000
      targetPort: 30000
      protocol: TCP
      name: metrics-30000
#    - port: 30001
#      targetPort: 30001
#      protocol: TCP
#      name: metrics-30001
  clusterIP: None # 必须设置为 None，表示这是一个 Headless Service
  selector: {}


---
# 定义 Endpoints，指定外部服务的地址
apiVersion: v1
kind: Endpoints
metadata:
  name: llm
  namespace: monitor
subsets:
  - addresses:
      - ip: 10.1.8.109
      - ip: 10.1.8.110
      - ip: 10.1.5.100
      - ip: 10.1.5.151
      - ip: 10.1.5.153
    ports:
      - port: 30000
        name: metrics-30000
# 非 30000 端口
#  - addresses:
#      - ip: 10.1.8.109
#      - ip: 10.1.5.151
#    ports:
#      - name: metrics-30001
#        port: 30001


---
# 定义 ServiceMonitor，用于 Prometheus 监控
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm
  namespace: monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: llm
  endpoints:
    - port: metrics-30000
      interval: 20s
      path: /metrics
      relabelings:
        # 见名知意的 instance 标签：模型名_GPU型号_IP
        - sourceLabels: [ __address__ ]
          targetLabel: instance
          regex: "(10.1.8.109|10.1.8.110):.*"
          replacement: "MiniMax-M2.5_GB200_$1"
        - sourceLabels: [ __address__ ]
          targetLabel: instance
          regex: "(10.1.5.100):.*"
          replacement: "GLM-5_B200_$1"
        - sourceLabels: [ __address__ ]
          targetLabel: instance
          regex: "(10.1.5.151|10.1.5.153):.*"
          replacement: "GLM-5_H200_$1"
#    - port: metrics-30001
#      interval: 20s
#      path: /metrics
#      relabelings:
#        # 见名知意的 instance 标签：模型名_GPU型号_IP
#        - sourceLabels: [ __address__ ]
#          targetLabel: instance
#          regex: "(10.1.8.109|10.1.8.110):.*"
#          replacement: "MiniMax-M2.5_GB200_$1"
