apiVersion: v2
appVersion: 1.1.0
description: A Helm chart for Deploying the Percona Operator for MySQL (based on Percona
  Server for MySQL)
home: https://docs.percona.com/percona-operator-for-mysql/ps/
maintainers:
- email: julio.pasinatto@percona.com
  name: jvpasinatto
- email: natalia.marukovich@percona.com
  name: nmarukovich
- email: eleonora.zinchenko@percona.com
  name: eleo007
name: ps-operator
version: 1.1.0
